"""empty message

Revision ID: 07b03228a0d7
Revises: e2afffa6ba1d
Create Date: 2020-10-27 14:29:10.949218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b03228a0d7'
down_revision = 'e2afffa6ba1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phase', sa.Column('can_create_task', sa.Boolean(), nullable=False))
    op.add_column('task', sa.Column('user_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'user_id')
    op.drop_column('phase', 'can_create_task')
    # ### end Alembic commands ###
